import streamlit as st
import os
from llama_index.core.llms import ChatMessage
from llama_index.llms.openai import OpenAI

openai_api_key = os.environ["OPENAI_API_KEY"]

def format_student_data(student_data, csv_description):
    """
    This function generates a prompt for the LLM to format the student data
    based on the provided CSV description. The formatted data will be used
    in subsequent steps for generating report card comments.
    """
    formatted_data_prompt = f"""
## Task: Format Student Data Based on CSV Description

You are given student data and a description of the CSV structure. Use the description to properly format the student data in a clear and structured way. DO NOT REMOVE ANY DATA. 

Below is the CSV description, followed by the student data.

### CSV Description:

{csv_description}

### Student Data (to be formatted):

{student_data}

Please format the student data according to the CSV description, ensuring clarity and consistency. RESPOND ONLY WITH THE REFORMATTED DATA TABLE.
"""
    return formatted_data_prompt

# Function to create a prompt for organizing instructions and parameters into a clear, structured prompt
def create_comment_prompt(instructions, sentence_range):
    """
    This function generates a clear and structured prompt based on the instructions
    and parameters for writing personalized report card comments.
    """
    formatted_instructions_prompt = f"""
## Task: Generate a Clear and Comprehensive LLM Prompt for Writing Report Card Comments

Your task is to generate a well-organized, easy-to-understand, and comprehensive prompt that will instruct an LLM to write personalized report card comments for ALL OF THE STUDENTS. 
The comments should follow the tone and guidelines provided below.

The prompt should include instructions that each comment should be between {sentence_range[0]} and {sentence_range[1]} sentences.

### User Instructions for Writing Comments:

{instructions}

### Response Formatting

RESPOND ONLY WITH THE PROMPT.
"""
    return formatted_instructions_prompt

class ReportCardCommentor:
    """
    A class designed to interact with an LLM (Large Language Model) to generate personalized
    report card comments for students based on provided data and user instructions.

    The class takes student data, a CSV description, specific comment-writing instructions, 
    and preference parameters (such as formality and specificity levels) to construct a 
    structured LLM prompt. It communicates with the LLM to format the student data, generate 
    the initial comments, and provide responses to user inputs for fine-tuning the comments.

    Attributes:
        llm (OpenAI): An instance of the OpenAI class used to interact with the LLM model.
        message_history (list): A history of messages exchanged between the user and the LLM, 
                                starting with a system prompt and user-provided data.
        init_comments (str): The initial comments generated by the LLM for the provided student data.
        prompt1 (str): The system-level task prompt provided to the LLM for comment generation.
        prompt2 (str): The user-level prompt, combining formatted instructions and student data.

    Methods:
        user_input(message):
            Accepts additional user input to update the comment generation process, interacting 
            with the LLM using the stored message history.
        
        get_initial_comments():
            Returns the initial set of report card comments generated for the student data.
        
        produce_list(comments):
            Reformats the LLM-generated comments into a list where each student's comment is 
            on a new line. This list format is suitable for copying into a spreadsheet or other 
            applications requiring one comment per row.
    """
    def __init__(self, student_data, csv_description, instructions, sentence_range, model="gpt-4o-mini"):
    
        # Initializing AI Model Interaction
        self.llm = OpenAI(model=model, api_key=openai_api_key)
    
        # Format initial prompt for LLM to format student data
        data_prompt = format_student_data(student_data, csv_description)
        # Use LLM to format data
        messages = [ChatMessage(role="system", content="You are designed to format data nicely."),
                    ChatMessage(role="user", content=data_prompt),]
        formatted_data = self.llm.chat(messages).message.content

        # Format initial prompt for LLM to generate instruction prompt
        instructions_prompt = create_comment_prompt(instructions, sentence_range)
        # Use LLM to format instructions
        messages = [ChatMessage(role="system", content="You are designed to develop effective LLM prompts."),
                    ChatMessage(role="user", content=instructions_prompt),]
        formatted_instructions = self.llm.chat(messages).message.content
    
        # Instance of LLM with chat history
        system_prompt = f"""
## Task: Generate Report Card Comments for Each Student

You are an experienced teacher who excels at writing report card comments.

Your task is to write personalized and thoughtful report card comments for each student, based on the student data and instructions provided by the user. 

### Response Formatting

You should produce a comment for each student, formatted in a markdown table. 

After providing the comments, ask the user for feedback on whether the comments meet the requirements, asking if any adjustments are needed.
"""
        
        init_prompt = f"""
Create comments for each student based on the instructions and data below.

## Instructions

{formatted_instructions}

## Student Data

{formatted_data}
"""

        self.message_history = [ChatMessage(role="system", content=system_prompt),
                                ChatMessage(role="user", content=init_prompt),]
        response = self.llm.chat(self.message_history)
        self.message_history.append(response.message)
        self.init_comments = response.message.content

    def user_input(self, message):
        # Add user prompt to history
        self.message_history.append(ChatMessage(role="user", content=message))
        # Prompt LLM with history
        response = self.llm.chat(self.message_history)
        # Add response to history
        self.message_history.append(response.message)
        return response.message.content

    def get_initial_comments(self):
        return self.init_comments

    def produce_list(self, comments):
        system_prompt = f"""
The user will provide you with the output from an LLM.

Your task is to take the report card comments within this output and reformat this information.

The comments should be formatted so that there is ONE STUDENT's COMMENT ON EACH LINE.

Comments should be written in the same order that they are received. 

Ignore any text outside of the original table.

Your response should just be the list of comments without anything else.
"""
    
        user_prompt = f"""
Reformat the comments below into a single list so that I can copy them into a column in Excel - one student per row.
    
## Comments
    
{comments}
"""

        messages = [ChatMessage(role="system", content=system_prompt),
                    ChatMessage(role="user", content=user_prompt),]
        formatted_comments = self.llm.chat(messages).message.content
        return formatted_comments
        
        
