[server]
maxUploadSize = 25

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
primaryColor="#A8D5BA"  # Pale green
backgroundColor="#FFFFFF"  # White
secondaryBackgroundColor="#E0F2E9"  # Lighter pale green
textColor="#2F4F4F"  # Dark greenish-gray for contrast
font="sans serif"

[ui]
hideTopBar = true